---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R projects $DEPLOYPATH
    - /bin/cp -f *.html $DEPLOYPATH
    - /bin/cp -f robots.txt $DEPLOYPATH
